---
title: "logical"
output: html_document
date: "2023-11-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())


library(rvest)
library(plyr)
library(ggiraph)
library(RColorBrewer)
library(wbstats)
library(readxl)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(countrycode)
library(data.table)
library(ISOcodes)
library(gtsummary)
library(faraway)
library(caret)
```

```{r}
##This is the file that includes the regression analyses 

##Import data 
regressiondata = read.csv("sexdisease.csv", stringsAsFactors = TRUE)%>%
  select(`ParentLocation`, `Location`, `Period`, `Dim2`, `Dim1`, `FactValueNumeric`)
as.data.frame(regressiondata)



##Only looking at 2016 and only looking at cumulative sex data
diseases2016 = filter(regressiondata, regressiondata$Period == "2016") 
diseases2016 = filter(diseases2016, diseases2016$Dim1 != "Both sexes")
colnames(diseases2016)[colnames(diseases2016) == "Location"] <- "Name"


##Import the dataframe with all variables from dataset prep.Rmd

allvariables = read.csv("allvariables.csv", stringsAsFactors = TRUE)

##Combine
diseases = left_join(diseases2016, allvariables, by = "Name")
diseases = as_tibble(diseases) 


```

```{r}

## This is a cumulative regression model that includes all of the countries and regions 

lmod = glm(cbind(FactValueNumeric, Name) ~ PercentObesityCrude + PercentAlcoholConsumers + MeanSystolic + MeanCholesterol + HDI.rank...1 + Life.expectancy.at.birth, family = binomial, diseases)

lmod %>%
  tbl_regression() %>%
  bold_labels() %>%
  bold_p(t = 0.05)


pchisq(as.numeric(lmod$deviance), as.numeric(lmod$df.residual), lower = FALSE)

plot(lmod)
halfnorm(hatvalues(lmod), ylab = "Sorted leverages")

diseases %>%
  slice(c(536, 466)) %>%
  print()
## Japan - female, cardiovascular disease and Italy - male, respiratory disease are extreme outlier 

drop = drop1(lmod, test = "Chi")
dropsort = drop[order(drop$`Pr(>Chi)`),]

##This data shows that the model does not have a good fit probably due to the high levels of complexity of noncommunicable disease mortality 

```

```{r}
##This is a regression model that excludes the Europe region in the training and sees if the model can be predictive of that region 

diseases.no.eu = filter(diseases, diseases$ParentLocation.x != "Europe")
diseases.eu = filter(diseases, diseases$ParentLocation.x == "Europe")

lmod.eu = glm(cbind(FactValueNumeric, Name) ~ PercentObesityCrude + PercentAlcoholConsumers + MeanSystolic + MeanCholesterol + HDI.rank...1 + Life.expectancy.at.birth, family = binomial, diseases.no.eu)

lmod.eu %>%
  tbl_regression() %>%
  bold_labels() %>%
  bold_p(t = 0.05)


pchisq(as.numeric(lmod.eu$deviance), as.numeric(lmod.eu$df.residual), lower = FALSE)

plot(lmod.eu)
halfnorm(hatvalues(lmod.eu), ylab = "Sorted leverages")


drop = drop1(lmod.eu, test = "Chi")
dropsort = drop[order(drop$`Pr(>Chi)`),]

pred1 = predict(lmod.eu, newdata = diseases.eu)

rmse = sqrt(sum((exp(pred1) - diseases.eu$FactValueNumeric)^2)/length(diseases.eu$FactValueNumeric))
c(RMSE = rmse, R2 = summary(lmod.eu)$r.squared)

par(mar=c(1,1,1,1))
plot(diseases.eu$FactValueNumeric, pred1)




```